### ISSUE TITLE
undefined method `strftime' for "20161214104743":String

### ISSUE THREAD

**Issue by map7** [sgruhier/capistrano-db-tasks#105]
When using capistrano-db-tasks with capistrano 3.7.0 on a ruby 2.2.5, with rails 3.0 I get the following error;

NoMethodError: undefined method `strftime' for "20161214104743":String
```
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/database.rb:45:in `c
urrent_time'                                                                          
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/database.rb:49:in `o
utput_file'                                                                           
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/database.rb:148:in `
db_dump_file_path'                                                                    
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/database.rb:131:in `
clean_dump_if_needed'                                                                 
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/database.rb:215:in `
ensure in remote_to_local'                                                            
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/database.rb:215:in `
remote_to_local'                                                                      
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/dbtasks.rb:41:in `bl
ock (4 levels) in <top (required)>'                                                   
/usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sshkit-1.11.4/lib/sshkit/backe
nds/abstract.rb:29:in `instance_exec'                                                 
/usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sshkit-1.11.4/lib/sshkit/backe
nds/abstract.rb:29:in `run'                                                           
/usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sshkit-1.11.4/lib/sshkit/runne
rs/parallel.rb:12:in `block (2 levels) in execute'                                    
NoMethodError: undefined method `strftime' for "20161214104743":String
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/database.rb:45:in `c
urrent_time'                                                                          
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/database.rb:49:in `o
utput_file'                                                                           
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/database.rb:148:in `
db_dump_file_path'                                                                    
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/database.rb:121:in `
dump'                                                                                 
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/database.rb:213:in `
remote_to_local'                                                                      
/home/map7/code/capistrano-db-tasks-master/lib/capistrano-db-tasks/dbtasks.rb:41:in `bl
ock (4 levels) in <top (required)>'                                                   
/usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sshkit-1.11.4/lib/sshkit/backe
nds/abstract.rb:29:in `instance_exec'                                                 
/usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sshkit-1.11.4/lib/sshkit/backe
nds/abstract.rb:29:in `run'                                                           
/usr/local/rbenv/versions/2.2.5/lib/ruby/gems/2.2.0/gems/sshkit-1.11.4/lib/sshkit/runne
rs/parallel.rb:12:in `block (2 levels) in execute'                                    
Tasks: TOP => db:pull => db:local:sync
```

To get around this error I had to change the code in database.rb to

```
    def current_time
      Time.zone.now.to_datetime.strftime("%Y-%m-%d-%H%M%S")
    end
```

**Comment by map7** [comment]
Fixed in 0.6
