### ISSUE TITLE
NameError: uninitialized constant Rails

### ISSUE THREAD

**Issue by kiddrew** [sgruhier/capistrano-db-tasks#80]
Apologies if this is a n00b question (I'm a cap n00b), but I'm getting this error when trying to do a db:pull from production.  Any idea why?

**Comment by kiddrew** [comment]
Here's a full trace:

```
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke rvm:hook (first_time)
** Execute rvm:hook
** Invoke rvm:check (first_time)
** Execute rvm:check
** Invoke bundler:map_bins (first_time)
** Execute bundler:map_bins
** Invoke deploy:set_rails_env (first_time)
** Execute deploy:set_rails_env
** Invoke deploy:set_linked_dirs (first_time)
** Execute deploy:set_linked_dirs
** Invoke deploy:set_rails_env
** Invoke rvm1:hook (first_time)
** Execute rvm1:hook
INFO [402f3357] Running /usr/bin/env mkdir -p /var/www/ilf-cms/rvm1scripts/ as deploy@ilf-web1
INFO [402f3357] Finished in 0.191 seconds with exit status 0 (successful).
INFO Uploading /Users/andrew/.rvm/gems/ruby-2.3.0/gems/rvm1-capistrano3-1.4.0/script/rvm-auto.sh 100.0%
INFO [d6490632] Running /usr/bin/env chmod +x /var/www/ilf-cms/rvm1scripts/rvm-auto.sh as deploy@ilf-web1
INFO [d6490632] Finished in 0.196 seconds with exit status 0 (successful).
** Invoke db:pull (first_time)
** Invoke db:local:sync (first_time)
** Execute db:local:sync
cap aborted!
NameError: uninitialized constant Rails
(erb):4:in `<main>'
/Users/andrew/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `eval'
/Users/andrew/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/erb.rb:864:in `result'
/Users/andrew/.rvm/gems/ruby-2.3.0/gems/capistrano-db-tasks-0.4/lib/capistrano-db-tasks/database.rb:114:in `initialize'
/Users/andrew/.rvm/gems/ruby-2.3.0/gems/capistrano-db-tasks-0.4/lib/capistrano-db-tasks/dbtasks.rb:35:in `new'
/Users/andrew/.rvm/gems/ruby-2.3.0/gems/capistrano-db-tasks-0.4/lib/capistrano-db-tasks/dbtasks.rb:35:in `block (4 levels) in <top (required)>'
/Users/andrew/.rvm/gems/ruby-2.3.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:15:in `instance_exec'
/Users/andrew/.rvm/gems/ruby-2.3.0/gems/sshkit-1.8.1/lib/sshkit/backends/abstract.rb:15:in `run'
/Users/andrew/.rvm/gems/ruby-2.3.0/gems/sshkit-1.8.1/lib/sshkit/runners/parallel.rb:13:in `block (2 levels) in execute'
Tasks: TOP => db:pull => db:local:sync
```

**Comment by kiddrew** [comment]
Never mind.  My fault.

**Comment by streetlogics** [comment]
@kiddrew what was your issue?  I apparently am doing the same thing by triggering the same error but am not seeing anything wrong.

**Comment by kiddrew** [comment]
I had a line in my db config that set the db name based on the app name.

```
database: <%= Rails.application.engine_name.gsub(/_application/,'').downcase %>_development
```

The Rails constant apparently doesn't exist in the Capistrano scope.

**Comment by streetlogics** [comment]
@kiddrew thanks for the reply!  I found a similar line almost exactly the same time as I saw this response after doing some debugging on my own fork.
